### PR TITLE
Added sections to web-scraper input schema

### PR DESCRIPTION
**Pull request by drobnikj**
I will update the other input schema after we agree on web-scraper.
 
web-scraper2

### CODE REVIEW

**Comment by jancurn** [comment]
The `jQuery and Underscore` section with just `jQuery` and `Underscore` options doesn't make sense. Also, the `Security` settings belong neither to `Proxy configuration` nor `Browser masking`.  Why not just having 3 simples sections like?

Basic settings (by default expanded?)
Advanced settings
Performance and limits

**Comment by mtrunkat** [comment]
The sections can include a description with help text. So I would keep Proxy Configuration & Browser masking as it's the most common problem every new user must face and we can describe the problem there briefly and link some KB article. 

So what about:

Basic
Proxy configuration & browser masking (can we find a better name??)
Advanced configuration
Performance and limits

And I'd merge debugging section to basic as it's the first thing user should try when it something doesn't work and security section into advanced as it's not so important.

What do you think?

**Comment by mnmkng** [comment]
I actually like the way @drobnikj split it. I'd just rename `jQuery & Underscore` to `Libraries`, because we were talking about including Moment.js which people use all the time and it might be a good opportunity to add more, if we have a nice section for them.

`Proxy Configuration & Browser masking` could perhaps be renamed to `Proxy & Browser Configuration`

And I would keep `Debugging` because we could add more debugging options there such as Live View or Debugger. Currently, Live View is forced for all Web Scraper runs.

So I'd go with:

Basic
Debugging
Proxy & Browser Configuration
Libraries
Performance & Limits
Advanced

Remember that we're still missing options that were in the original Crawler, so the number of checkboxes and fields will only grow.

**Comment by jancurn** [comment]
So how about:

Basic settings
Proxies and browser masking
Advanced settings
Performance and limits

**Comment by jancurn** [comment]
@mnmkng Having 6 sections is simply way too many, especially when the sections contain as little as 2 controls. Basically, you have to expand a bar with a height of e.g. 30 pixels, just to see content with height of 60 pixels...that's not a great UX. We really need to keep it simple and balanced, 3-4 sections, with a similar amount of inputs for each.

**Comment by drobnikj** [comment]
I like more sections because it breaks the large form into readable pieces. Plus with caption title, you can easily find what you are interested in.

**Comment by drobnikj** [comment]
Can we agree on 5 section?

Basic
Debugging
Proxy & Browser Configuration
Performance & Limits
Advanced

I will move Libraries into Basic and we can split it into a new section when we will have more libraries in the future.

**Comment by jancurn** [comment]
Really, let's move "Debugging" into "Basic", having a section with just 2 input controls is really shitty UX.

**Comment by jakubbalada** [comment]
Debugging would be better in Advanced, not Basic. Otherwise, 4 sections are ok for me

**Comment by itstrangvu** [comment]
I'd put it as follows: 
Basic settings
Proxy (How about "Anonymous browsing" title?) 
Advanced settings (Advanced + jQuery and underscore + Debugging)
Performance and limits

Please, also replace '&'s with simple 'and's.

**Comment by drobnikj** [comment]
Updated version with feedback

**Comment by mtrunkat** [comment]
I think that these 4 sections are enough. But

- security and cookies should be a part of advanced
- I'd consider moving debugging section to basic for now

**Comment by mtrunkat** [comment]
Added https://github.com/apifytech/actor-scraper/issues/31

**Comment by mnmkng** [comment]
I like "Anonymous browsing". 👍 It helps ppl who have no idea what proxies are and people who understand what proxies are will be able to find them there easily.

**Comment by jancurn** [comment]
@drobnikj One more thing, `Proxy & Browser configuration` should be `Proxy and browser configuration`, and the same for `Performance & Limits` ... basically use `and` and avoid capitalization (we never use it)

**Pull request merged**
